version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    container_name: backend
    restart: always
    build: ./backend
    env_file:  
      - ./.env
    volumes:
      - static_value:/app/src/static/
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
    depends_on:
      - backend

  ngrok:
    image: ngrok/ngrok:alpine 
    container_name: ngrok
    profiles:
      - "host"
    command: http host.docker.internal:80 --domain=${SERVER_HOST} --host-header=127.0.0.1
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"

volumes:
  postgres_data:
  static_value:
