GENRE_TO_ID = {
    "Action": 1,
    "Adventure": 2,
    "Animation": 3,
    "Biography": 4,
    "Comedy": 5,
    "Crime": 6,
    "Documentary": 7,
    "Drama": 8,
    "Family": 9,
    "Fantasy": 10,
    "Noir": 11,
    "History": 12,
    "Horror": 13,
    "Music": 14,
    "Musical": 15,
    "Mystery": 16,
    "Romance": 17,
    "Sci-Fi": 18,
    "Short": 19,
    "Sport": 20,
    "Thriller": 21,
    "War": 22,
    "Western": 23,
}
